apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  cohere-api-key: {{ .Values.secrets.cohereApiKey | b64enc | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
